trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

stages:
  - stage: Build
    pool:
      vmImage: "ubuntu-18.04"
    jobs:
      - job: Package
        steps:
          - task: UseGitVersion@5
            displayName: "Git Version"
            inputs:
              versionSpec: "5.0.0"
              useConfigFile: true
              configFilePath: "$(Build.SourcesDirectory)/GitVersion.yml"
          - task: Yarn@3
            displayName: "Install"
            inputs:
              ProjectDirectory: $(Build.SourcesDirectory)
          - task: Yarn@3
            displayName: "Update version"
            inputs:
              arguments: "version --new-version $(Build.BuildNumber) --no-git-tag-version"
              ProjectDirectory: $(Build.SourcesDirectory)        
          - task: Yarn@3
            displayName: "eslint-config-mocoding - Pack"
            condition:
            inputs:
              arguments: "pack --filename $(Build.StagingDirectory)/eslint-config-mocoding-$(Build.BuildNumber).tgz"
              projectDirectory: "$(Build.SourcesDirectory)"
          - task: PublishBuildArtifacts@1
            displayName: "eslint-config-mocoding - Publish"
            inputs:
              PathtoPublish: "$(Build.StagingDirectory)/eslint-config-mocoding-$(Build.BuildNumber).tgz"
              ArtifactName: npm-eslint-config-mocoding          
  - stage: Deploy
    dependsOn: Build
    condition: and(succeeded(), contains(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: "ubuntu-18.04"
    jobs:
      - deployment: DevBuild
        environment: "dev-builds"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: Npm@1
                displayName: "eslint-config-mocoding - Publish to npm (dev-builds)"
                inputs:
                  command: "custom"
                  customCommand: "publish $(Pipeline.Workspace)/npm-eslint-config-mocoding/eslint-config-mocoding-$(Build.BuildNumber).tgz"
                  customRegistry: "useFeed"
                  customFeed: "da7703d4-fb22-4933-b869-83f4264b7b84/e1336e71-3540-4a0c-830c-639112685b07"
  - stage: Release
    dependsOn: Build
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags/v'))
    pool:
      vmImage: "ubuntu-18.04"
    jobs:
      - deployment: Public
        environment: "public"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: GitHubRelease@1
                  displayName: "Update GitHub release"
                  inputs:
                    gitHubConnection: "github.com_offbeatful"
                    repositoryName: "mocoding-software/eslint-config-mocoding"
                    action: edit
                    tag: "v$(Build.BuildNumber)"
                    assets: "$(Pipeline.Workspace)/**/*.tgz"
                    assetUploadMode: replace
                - task: Npm@1
                  displayName: "eslint-config-mocoding - Publish to npm"
                  inputs:
                    command: "custom"
                    customCommand: "publish --access public $(Pipeline.Workspace)/npm-eslint-config-mocoding/eslint-config-mocoding-$(Build.BuildNumber).tgz"
                    customEndpoint: "public-npm"        
